name: 'Gource Action'
description: 'Visualisation action for source control repositories using gource.'
author: 'Norbert Bartko'

inputs:
  git-url:
    description: ''
    default: 'https://github.com/acaudwell/Gource.git'
    required: false
  git-token:
    description: ''
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'monitor'
  color: 'pruple'
