name: 'Gource Action'
description: 'Visualisation action for source control repositories using gource.'
author: 'Norbert Bartko'

inputs:
  git-url:
    description: ''
    default: './'
    required: true
  git-token:
    description: ''
    required: false
  logo-url:
    description: ''
    default: 'https://avatars1.githubusercontent.com/u/44036562?s=280&v=4'
    required: false
  gource-title:
    description: ''
    default: 'Title'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GIT_URL: ${{ inputs.git-url }}
    GIT_TOKEN: ${{ inputs.git-token }}
    LOGO_URL: ${{ inputs.logo-url }}
    GOURCE_TITLE: ${{ inputs.gource-title }}

branding:
  icon: 'monitor'
  color: 'pruple'
