name: 'Gource Action'
description: 'Visualisation action for source control repositories using gource.'
author: 'Norbert Bartko'

inputs:
  git-url:
    description: ''
    default: 'https://github.com/NBprojekt/writing-javascript-actions'
    required: false
  git-token:
    description: ''
    required: false
  logo-url:
    description: ''
    default: 'https://avatars1.githubusercontent.com/u/44036562?s=280&v=4'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'monitor'
  color: 'pruple'
