name: 'Gource Action'
description: 'Visualisation action for source control repositories using gource.'
author: 'Norbert Bartko'

inputs:
  git-url:
    description: 'Location of git repository. Can also be an remote repository e.g.: https://github.com/acaudwell/Gource.git'
    default: './'
    required: false
  git-token:
    description: 'If the providet repository is private the action need an topen with read scope.'
    default: ''
    required: false
  logo-url:
    description: 'Displayed icon on bottom right corner.'
    default: ''
    required: false
  gource-title:
    description: 'Display title on bottom left corner.'
    default: 'Title'
    required: false
  gource-resolution:
    description: 'Used gource resolution.'
    default: '1080p'
    required: false
  gource-fps:
    description: 'Used gource fps.'
    default: '60'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GIT_URL: ${{ inputs.git-url }}
    GIT_TOKEN: ${{ inputs.git-token }}
    LOGO_URL: ${{ inputs.logo-url }}
    GOURCE_TITLE: ${{ inputs.gource-title }}
    GOURCE_RESOLUTION: ${{ inputs.gource-resolution }}
    GOURCE_FPS: ${{ inputs.gource-fps }}

branding:
  icon: 'monitor'
  color: 'pruple'
