name: 'Gource Action'
description: 'Visualisation action for source control repositories using gource.'
author: 'Norbert Bartko'

inputs:
  git_url:
    description: 'Location of git repository. Can also be an remote repository e.g.: https://github.com/acaudwell/Gource.git'
    default: './'
    required: false
  git_token:
    description: 'If the provided repository is private, the action need an token with read scope.'
    default: ''
    required: false
  logo_url:
    description: 'Displayed icon on bottom right corner.'
    default: ''
    required: false
  avatars_url:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: ''
    required: false
  gource_title:
    description: 'Display title on bottom left corner.'
    default: 'Title'
    required: false
  gource_resolution:
    description: 'Used gource resolution.'
    default: '1080p'
    required: false
  gource_fps:
    description: 'Used gource fps.'
    default: '60'
    required: false
  gource_auto_skip_seconds:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '0.5'
    required: false
  gource_background_color:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '000000'
    required: false
  gource_font_color:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: 'FFFFFF'
    required: false
  gource_font_size:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '44'
    required: false
  gource_overlay_font_color:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: 'FFFFFF'
    required: false
  gource_camera_mode:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: 'overview'
    required: false
  gource_dir_depth:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '3'
    required: false
  gource_filename_time:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '2'
    required: false
  gource_hide_items:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: 'mouse,date,filenames'
    required: false
  gource_max_user_speed:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '500'
    required: false
  gource_seconds_per_day:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '0.1'
    required: false
  gource_time_scale:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '1.5'
    required: false
  gource_user_scale:
    description: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    default: '1.5'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'monitor'
  color: 'purple'
