
name: Gource Action Dev
on:
  push:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Current folder'
        run: ls -al

      - name: 'Gource Action'
        uses: ./
        with:
          git-url: ./
          avatars-url: ./avatars/*

      - name: 'Check output'
        run: ls -al ./

      - uses: actions/upload-artifact@v2
        with:
          name: gource
          path: ./gource
