name: Gource Action Dev
on:
  push:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Current folder'
        run: ls -al

      - name: 'Gource Action'
        uses: ./
        with:
          git_url: https://github.com/docker/cli
          title: 'Docker CLI'
          logo_url: 'https://user-images.githubusercontent.com/24683383/92395924-70189f80-f124-11ea-815c-aa4d9f4de29d.png'
          gource_resolution: '1080p'
          gource_fps: '60'
          gource_font_size: 40
          gource_start_date: '2016-04-18'
          gource_stop_date: '2019-12-31'

      - name: 'Check output'
        run: ls -al ./

      - uses: actions/upload-artifact@v2
        with:
          name: gource
          path: ./gource
