name: Gource Action Dev
on:
  push:
    branches:
      - master

jobs:
  dev-action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Current folder'
        run: ls -al

      - name: 'Gource Action'
        uses: ./
        with:
          git_url: ./
          gource_title: 'Gource Action Development'
          logo_url: 'https://user-images.githubusercontent.com/24683383/92398226-79a40680-f128-11ea-9f54-6ccbaca4a6a5.png'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          gource_start_date: '2020-08-25'
          gource_stop_date: '2020-09-06'

      - name: 'Check output'
        run: ls -al ./

      - uses: actions/upload-artifact@v2
        with:
          name: gource
          path: ./gource
