name: Gource Action Build
on:
  release:
    types:
      - published

jobs:
  gource-action:
    name: 'Local visualisation'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@master
        with:
          git_url: ./
          avatars_url: ./avatars/
          gource_title: 'Gource action'
          logo_url: 'https://user-images.githubusercontent.com/24683383/92398226-79a40680-f128-11ea-9f54-6ccbaca4a6a5.png'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource action
          path: ./gource/gource.mp4
