name: Gource Action Dev
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - master
      - 'dev/**'

jobs:
  # local-images:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: 'Current folder'
  #       run: ls -al

  #     - name: 'Gource Action'
  #       uses: ./
  #       with:
  #         git_url: ./
  #         avatars_url: ./avatars/
  #         gource_title: 'Gource Action Development'
  #         logo_url: ./logo.png
  #         avatars_auto_fetch: true

  #     - name: 'Check output'
  #       run: |
  #         ls -al ./
  #         ls -al ./gource

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: gource-local
  #         path: ./gource
  #         retention-days: 1

  # test-new-url-regex:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: 'Current folder'
  #       run: ls -al

  #     - name: 'Gource Action'
  #       uses: ./
  #       with:
  #         git_url: ./
  #         avatars_url: ./avatars/
  #         gource_title: 'Gource Action Development'
  #         logo_url: https://raw.githubusercontent.com/glotaran/pyglotaran/main/docs/source/images/glotaran.png?raw=true
  #         avatars_auto_fetch: true

  #     - name: 'Check output'
  #       run: |
  #         ls -al ./
  #         ls -al ./gource

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: gource-local
  #         path: ./gource
  #         retention-days: 1

  avatar-issues:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          avatars_auto_fetch: true
          gource_title: 'NoitaMP Gource master'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          gource_auto_skip_seconds: 0.1
          gource_seconds_per_day: 0.1

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4