name: Gource Action Build
on:
  release:
    types:
      - published

jobs:
  gource-action:
    name: 'Local visualisation'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: BoundfoxStudios/action-gource@master
        with:
          git_url: ./
          gource_title: 'Gource Action'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v3
        with:
          name: Gource action
          path: ./gource/gource.mp4